<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="foreact"
    nsURI="http://foreact/model"
    nsPrefix="foreact">

  <!-- ============================================================= -->
  <!-- Core                                                          -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ForecastAssuranceProject" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//DatasetVersion" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldModel" eType="#//FieldModel" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioModel" eType="#//ScenarioModel" containment="true" lowerBound="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodSet" eType="#//MethodSet" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comparisonModel" eType="#//ForecastComparisonModel" containment="true" lowerBound="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signalModel" eType="#//SignalModel" containment="true" lowerBound="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisionModel" eType="#//DecisionModel" containment="true" lowerBound="0"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Dataset Entities                                              -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="DatasetVersion" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rawFields" eType="#//RawField" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="RawField" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missingRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Semantic Field Entities                                       -->
  <!-- VersionField = forecast vintage/run field                     -->
  <!-- HorizonField = target period being forecast                   -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="FieldModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completenessScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" eType="#//SemanticField" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SemanticField" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="businessName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semanticType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//DirectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceColumn" eType="#//RawField" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="VersionField" eSuperTypes="#//SemanticField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="HorizonField" eSuperTypes="#//SemanticField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="granularity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TargetField" eSuperTypes="#//SemanticField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="riskDirection" eType="#//DirectionKind"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DriverField" eSuperTypes="#//SemanticField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedEffect" eType="#//DirectionKind"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Scenario, Assumption, and Evidence Entities                   -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="ScenarioModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptions" eType="#//AssumptionElement" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evidence" eType="#//EvidenceArtifact" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AssumptionElement" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="#//ConfidenceKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validityPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" eType="#//EvidenceArtifact" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ScenarioAssumption" eSuperTypes="#//AssumptionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DataCenterCommitment" eSuperTypes="#//AssumptionElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="committedLoadMW" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedInServiceDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affects" eType="#//TargetField" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="EvidenceArtifact" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="#//ConfidenceKind"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Method Entities                                               -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="MethodSet" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" eType="#//AnalysisMethod" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AnalysisMethod" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="VarianceMethod" eSuperTypes="#//AnalysisMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeVarianceThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="VolatilityMethod" eSuperTypes="#//AnalysisMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highVolatilityThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statistic" eType="#//VolatilityStatisticKind"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ConfidenceMethod" eSuperTypes="#//AnalysisMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidenceRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Forecast Comparison Entities                                  -->
  <!-- ForecastVintage = one forecast run/vintage                    -->
  <!-- ForecastObservation = one value for one vintage, target,       -->
  <!--                       and target period                        -->
  <!-- ForecastVarianceRecord = two-vintage delta                     -->
  <!-- ForecastVolatilityRecord = multi-vintage dispersion            -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="ForecastComparisonModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="focusPeriodStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="focusPeriodEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="vintages" eType="#//ForecastVintage" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baselineVintage" eType="#//ForecastVintage" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentVintage" eType="#//ForecastVintage" lowerBound="1"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="varianceRecords" eType="#//ForecastVarianceRecord" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="volatilityRecords" eType="#//ForecastVolatilityRecord" containment="true" upperBound="-1"/>

    <eStructuralFeatures xsi:type="ecore:EReference" name="versionField" eType="#//VersionField" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizonField" eType="#//HorizonField" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ForecastVintage" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vintageDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observations" eType="#//ForecastObservation" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeAssumptions" eType="#//AssumptionElement" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ForecastObservation" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TargetField" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ForecastVarianceRecord" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deltaPct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TargetField" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baselineObservation" eType="#//ForecastObservation" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentObservation" eType="#//ForecastObservation" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computedBy" eType="#//VarianceMethod" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ForecastVolatilityRecord" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatilityScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stdDev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observationCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TargetField" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observations" eType="#//ForecastObservation" lowerBound="2" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computedBy" eType="#//VolatilityMethod" lowerBound="1"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Signal Entities                                               -->
  <!-- Signals classify analytical records for decision support.      -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="SignalModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signals" eType="#//Signal" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Signal" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classification" eType="#//SignalClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computedFor" eType="#//TargetField" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computedBy" eType="#//AnalysisMethod" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="VarianceSignal" eSuperTypes="#//Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variancePct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" eType="#//ForecastVarianceRecord" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="VolatilitySignal" eSuperTypes="#//Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatilityScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" eType="#//ForecastVolatilityRecord" lowerBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ConfidenceSignal" eSuperTypes="#//Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidenceLevel" eType="#//ConfidenceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" eType="#//EvidenceArtifact" upperBound="-1"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Decision Entities                                             -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EClass" name="DecisionModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" eType="#//DecisionPolicy" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cards" eType="#//DecisionCard" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DecisionPolicy" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" eType="#//DecisionRule" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DecisionRule" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//ActionKind"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="DecisionCard" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recommendedAction" eType="#//ActionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TargetField" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesSignals" eType="#//Signal" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliesPolicy" eType="#//DecisionPolicy" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" eType="#//EvidenceArtifact" upperBound="-1"/>
  </eClassifiers>


  <!-- ============================================================= -->
  <!-- Enumerations                                                  -->
  <!-- ============================================================= -->

  <eClassifiers xsi:type="ecore:EEnum" name="DirectionKind">
    <eLiterals name="increase"/>
    <eLiterals name="decrease"/>
    <eLiterals name="neutral"/>
    <eLiterals name="unknown"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="ConfidenceKind">
    <eLiterals name="low"/>
    <eLiterals name="medium"/>
    <eLiterals name="high"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="SignalClass">
    <eLiterals name="low"/>
    <eLiterals name="moderate"/>
    <eLiterals name="high"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="ActionKind">
    <eLiterals name="no_action"/>
    <eLiterals name="monitor"/>
    <eLiterals name="review"/>
    <eLiterals name="act"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="VolatilityStatisticKind">
    <eLiterals name="std_dev"/>
    <eLiterals name="coefficient_of_variation"/>
    <eLiterals name="range"/>
    <eLiterals name="mean_absolute_revision"/>
    <eLiterals name="custom"/>
  </eClassifiers>

</ecore:EPackage>